# Generated by Django 5.0.1 on 2024-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_grade_student_alter_grade_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
