# Generated by Django 5.0.2 on 2024-02-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_grade_letter_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.student_model')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.subjectmodel')),
            ],
        ),
    ]
